/* Reproducible HistoryOut v2 assets. UI is real; qa-lib supplies fictional history only. */
const fs = require('node:fs/promises');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const {chromium,startServer,openFixture,installFixture} = require('./qa-lib.cjs');
const ROOT=path.resolve('launch/assets');
const raw=n=>path.join(ROOT,'raw',n);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const q=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const BRAND={ink:'#122c48',blue:'#185adb',accent:'#79aaff'};
async function folder(){for(const p of ['raw','screenshots','video','source'])await fs.mkdir(path.join(ROOT,p),{recursive:true});}
async function moveTo(page,locator,offset=24){await locator.evaluate((el,top)=>window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-top,behavior:'instant'}),offset);await sleep(150);}
async function omitSupportForMarketing(page){
 // Capture-only omission requested by the user. The installed extension is unchanged.
 await page.evaluate(()=>document.getElementById('coffee-support-note')?.parentElement?.parentElement?.setAttribute('data-marketing-omit','support'));
 await page.addStyleTag({content:'[data-marketing-omit="support"],a[href*="buymeacoffee.com"]{display:none!important}*,*::before,*::after{animation:none!important;transition:none!important;caret-color:transparent!important}'});
 if(await page.getByRole('link',{name:'Buy me a coffee (opens in a new tab)'}).isVisible())throw new Error('Support strip visible in marketing capture');
}
async function preview(page){await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('heading',{name:/recap/}).waitFor();await sleep(200);}
async function setRange(page,label){await page.getByLabel('History range').click();await page.getByRole('option',{name:label,exact:true}).click();}
async function chooseColumns(page,keys){
 await page.getByLabel('Include', {exact:true}).click();
 const opts=page.getByRole('option'); const count=await opts.count();
 for(let i=0;i<count;i++){const opt=opts.nth(i);const name=(await opt.innerText()).split('\n')[0].trim();const checked=(await opt.getAttribute('aria-selected'))==='true';if(checked!==keys.map(k=>k.toLowerCase()).includes(name.toLowerCase()))await opt.click();}
 await page.keyboard.press('Escape');await sleep(450);
}
const stageCss=`*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:${BRAND.ink}}body{background:#f3f6fb}.stage{width:1280px;height:800px;position:relative;overflow:hidden;background:radial-gradient(ellipse at 90% 0%,#dce8ff 0,transparent 55%),#f3f6fb}.stage:after{content:'';position:absolute;left:48px;right:48px;bottom:28px;height:1px;background:#dbe2ed}.copy{position:absolute;left:64px;top:64px;width:580px}.brand{display:flex;align-items:center;gap:12px;font-size:24px;letter-spacing:-.7px;font-weight:750}.brand img{width:190px;height:70px;object-fit:contain;object-position:left center}.eyebrow{margin:66px 0 20px;font-size:13px;letter-spacing:2px;color:#5c7190;font-weight:750}.headline{margin:0;font-size:66px;line-height:1.06;letter-spacing:-3.5px;font-weight:780;max-width:580px}.headline .blue{color:${BRAND.blue}}.description{font-size:21px;line-height:1.48;color:#5e718c;max-width:490px;margin:26px 0}.points{display:grid;gap:15px;margin-top:30px;font-size:17px;line-height:1.35}.points>div{display:flex;align-items:flex-start;gap:12px}.check{height:22px;width:22px;border-radius:50%;background:#e0e9ff;color:${BRAND.blue};display:grid;place-items:center;font-size:13px;font-weight:800;flex-shrink:0}.note{font-size:12px;color:#7b8ba3;position:absolute;left:64px;bottom:49px}.frame{position:absolute;right:38px;top:28px;width:516px;height:744px;border:1px solid #cdd8e8;border-radius:20px;background:white;overflow:hidden;box-shadow:0 24px 58px #203d7020}.framebar{height:40px;display:flex;align-items:center;gap:7px;border-bottom:1px solid #e0e6f0;background:#fff;padding:0 14px;font-size:11px;color:#7c8a9f}.dot{width:7px;height:7px;border-radius:50%;background:#d5dfed}.framebar span{margin-left:auto;margin-right:auto}.capture{width:514px;height:703px;overflow:hidden;background:#f5f7fb;display:flex;justify-content:center;align-items:flex-start}.capture>img{width:500px;height:700px;object-fit:contain;display:block}.export .copy{width:475px}.export .headline{font-size:60px}.export .frame{width:665px;right:28px}.export .capture{width:663px;justify-content:flex-start}.export .capture>img{width:664px;height:700px}.stackshots{width:500px;height:700px;overflow:hidden}.saved-strip{background:#fff;padding:12px 16px;border-bottom:1px solid #e3e9f2}.saved-strip img{display:block;max-width:100%;height:auto}.stackshots>.mainshot{width:500px;display:block}.smallprint{font-size:14px;line-height:1.5;color:#6c7d96;margin-top:24px;max-width:440px}`;
function composition(scene){
 const content=scene.strip?`<div class="stackshots"><div class="saved-strip"><img src="/launch/assets/raw/${scene.strip}"></div><img class="mainshot" src="/launch/assets/raw/${scene.image}"></div>`:`<img src="/launch/assets/raw/${scene.image}">`;
 return `<!doctype html><html lang="en"><meta charset="utf-8"><style>${stageCss}</style><body><main class="stage ${scene.wide?'export':''}"><section class="copy"><div class="brand"><img src="/launch/assets/source/logo.svg" alt="HistoryOut"></div><div class="eyebrow">${scene.eyebrow}</div><h1 class="headline">${scene.title}</h1><p class="description">${scene.description}</p><div class="points">${scene.points.map(t=>`<div><span class="check">✓</span><span>${t}</span></div>`).join('')}</div>${scene.small?`<p class="smallprint">${scene.small}</p>`:''}</section><div class="frame"><div class="framebar"><i class="dot"></i><i class="dot"></i><i class="dot"></i><span>${scene.wide?'Your exported HTML file':'HistoryOut · Actual extension interface'}</span></div><div class="capture">${content}</div></div><p class="note">Actual working interface. Fictional demo history. Free, with no account.</p></main></body></html>`;
}
async function screenshots(browser,origin){
 const {page,context}=await openFixture(browser,origin,{viewport:{width:400,height:900},deviceScaleFactor:3});
 // Re-seed after the fixed demo clock applies so captures stay reproducible across dates.
 await page.evaluate(installFixture);
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('button')).some(button=>button.textContent.trim()==='Preview'&&!button.disabled));await sleep(400);await omitSupportForMarketing(page);await page.screenshot({path:raw('panel-initial-400.png')});await preview(page);
 await page.screenshot({path:raw('panel-daily-400.png'),fullPage:true});
 await page.setViewportSize({width:1120,height:900});await page.screenshot({path:raw('desktop-daily-1120.png'),fullPage:true});
 await page.setViewportSize({width:500,height:624});await moveTo(page,page.getByRole('heading',{name:"Today's recap"}));await page.screenshot({path:raw('01-daily-focus.png')});
 await page.getByRole('textbox',{name:'Search history titles or URLs'}).fill('research');
 await page.getByRole('checkbox',{name:/One row per URL/}).check();
 await page.getByRole('button',{name:'Save view',exact:true}).click();await page.getByRole('textbox',{name:'View name'}).fill('Website research');await page.getByRole('button',{name:'Save',exact:true}).click();
 const strip=page.getByText('Your saved views',{exact:true}).locator('..');await strip.screenshot({path:raw('saved-view-strip.png')});
 await page.setViewportSize({width:500,height:624});await moveTo(page,page.getByRole('heading',{name:'Your recent trail'}));await page.screenshot({path:raw('02-project-focus.png')});
 await page.getByRole('button',{name:'Reset filters',exact:true}).click();await setRange(page,'Custom dates');
 await page.getByLabel('Start date',{exact:true}).fill('2026-09-04');await page.getByLabel('End date',{exact:true}).fill('2026-09-05');await preview(page);
 await page.setViewportSize({width:500,height:700});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await sleep(250);await page.screenshot({path:raw('03-custom-dates.png')});
 await page.getByRole('heading',{name:'Start with a time range'}).locator('../..').screenshot({path:raw('custom-date-controls.png')});
 await page.getByRole('checkbox',{name:/One row per URL/}).check();await page.getByRole('checkbox',{name:'Remove URL queries & fragments'}).check();
 await page.getByRole('button',{name:'JSON, structured data',exact:true}).click();await chooseColumns(page,['Date','Time','Title','URL','Domain']);
 await page.getByLabel('Include',{exact:true}).click();await page.getByRole('listbox').locator('..').evaluate(el=>el.scrollTop=0);await sleep(50);await page.getByRole('listbox').locator('..').screenshot({path:raw('column-options.png')});await page.keyboard.press('Escape');await page.getByRole('listbox').waitFor({state:'hidden'});await sleep(300);
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await sleep(200);await page.screenshot({path:raw('04-clean-export.png')});
 await page.getByRole('button',{name:'HTML, readable in a browser',exact:true}).click();await chooseColumns(page,['Date','Title','URL']);
 await page.getByRole('group',{name:'Export file settings'}).screenshot({path:raw('export-format-controls.png')});
 await page.getByRole('group',{name:'Export file settings'}).locator('..').screenshot({path:raw('export-controls-card.png')});
 await page.getByRole('button',{name:/^Export \d/}).screenshot({path:raw('export-download-button.png')});
 const waitDownload=page.waitForEvent('download');await page.getByRole('button',{name:/^Export \d/}).click();const download=await waitDownload;await download.saveAs(path.join(ROOT,'demo-history.html'));
 const exported=await context.newPage();await exported.setViewportSize({width:760,height:800});await exported.goto(origin+'/launch/assets/demo-history.html');await exported.screenshot({path:raw('05-real-html-export.png')});
 await exported.setViewportSize({width:650,height:550});await exported.screenshot({path:raw('html-export-hero.png')});
 await exported.locator('table').evaluate(el=>el.scrollIntoView({block:'start'}));await exported.screenshot({path:raw('html-links-hero.png')});
 const scenes=[
 {file:'01-find-your-way-back.png',eyebrow:'01 / EXPORT YOUR BROWSER HISTORY',title:'Your history.<br><span class="blue">Your file.</span>',description:'Export the browsing history you need in a format you can use.',points:['CSV for spreadsheets','JSON for structured data','HTML for a readable file with links'],image:'04-clean-export.png'},
 {file:'02-return-to-your-research.png',eyebrow:'02 / MAKE THE FILE YOURS',title:'Your dates.<br><span class="blue">Your detail.</span>',description:'Choose a date range and the columns that belong in your export.',points:['Presets and custom dates','Choose the fields in your file','Preview before you download'],image:'03-custom-dates.png'},
 {file:'03-choose-your-time-range.png',eyebrow:'03 / READABLE HTML',title:'Export it.<br><span class="blue">Open it later.</span>',description:'Keep a readable history file with clickable links. Open it locally in a browser.',points:['Real downloaded HTML','Your chosen columns','Useful pages, ready to revisit'],image:'05-real-html-export.png',wide:true},
 {file:'04-export-only-what-matters.png',eyebrow:'04 / KEEP THE MATCHING PAGES',title:'Less noise.<br><span class="blue">Useful results.</span>',description:'Search and filter your history before exporting the pages you need.',points:['Search page titles and URLs','Filter by website','Keep the latest visit to each URL'],image:'02-project-focus.png'},
 {file:'05-a-file-you-can-use.png',eyebrow:'05 / USEFUL EXTRAS, INCLUDED',title:'Pick it up<br><span class="blue">tomorrow.</span>',description:'Daily recaps and saved views help you revisit useful pages and repeat an export.',points:['A recap of available history','Return to your saved filters','Every feature stays free'],image:'01-daily-focus.png',strip:'saved-view-strip.png'},
 ];
 const art=await browser.newPage({viewport:{width:1280,height:800}});
 for(const scene of scenes){const name=scene.file.replace('.png','.html');await fs.writeFile(path.join(ROOT,'source',name),composition(scene));await art.goto(origin+'/launch/assets/source/'+name);await art.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await art.screenshot({path:path.join(ROOT,'screenshots',scene.file)});console.log('Screenshot:',scene.file);}
 await fs.writeFile(path.join(ROOT,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>HistoryOut export screenshots</title><style>body{font:18px/1.6 system-ui;background:#faf9f6;color:#122c48;max-width:1280px;margin:50px auto;padding:20px}img{display:block;width:100%;margin:20px 0 50px}</style><h1>HistoryOut export screenshots</h1><p>Actual product controls with fictional history. Optional support is omitted in marketing captures only.</p><section><h2>The 25-second HistoryOut demo</h2><p>Export formats first, customization next, useful extras last. Quick transitions and a complete branded ending.</p><video controls preload="metadata" style="width:100%;border-radius:12px" poster="video-v5/historyout-poster.png"><source src="video-v5/historyout-export-demo.mp4" type="video/mp4"><track kind="captions" src="video-v5/historyout-captions.vtt" srclang="en" label="English"></video><p><a href="video-v5/historyout-export-demo.mp4" download>Download video</a> · <a href="video-v5/historyout-captions.srt" download>Download captions</a> · <a href="https://youtu.be/cGybkRSkk2Y">Watch on YouTube</a></p></section>${scenes.map(s=>`<h2>${s.eyebrow}</h2><img src="screenshots/${s.file}" alt="${q(s.eyebrow)}">`).join('')}</html>`);
 await context.close();
}
function videoStage(){return `<!doctype html><html lang="en"><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#122c48}body{background:#f3f6fb}.stage{position:relative;width:1280px;height:720px;background:radial-gradient(ellipse at 0% 0%,#deebff,transparent 65%),#f3f6fb}.copy{position:absolute;left:50px;top:44px;width:428px}.brand{display:flex;align-items:center;gap:11px;font-size:24px;font-weight:750;letter-spacing:-.8px}.brand img{width:43px;height:43px}.step{font-size:12px;color:#56708e;letter-spacing:2px;font-weight:750;margin-top:57px}h1{font-size:52px;letter-spacing:-2.6px;line-height:1.07;margin:20px 0 24px;font-weight:780}.blue{color:#185adb}.lead{font-size:20px;line-height:1.5;color:#64758d;max-width:390px}.caption{position:absolute;left:50px;bottom:82px;width:415px;background:#122c48;color:#fff;padding:20px 22px;border-radius:13px;font-size:18px;line-height:1.42}.note{position:absolute;left:50px;bottom:38px;font-size:11px;color:#75869c}.frame{position:absolute;right:30px;top:24px;width:746px;height:660px;border-radius:18px;overflow:hidden;border:1px solid #ccd8e8;background:#fff;box-shadow:0 24px 58px #203d7020}.bar{height:36px;display:flex;align-items:center;padding:0 16px;gap:7px;border-bottom:1px solid #e0e6f0;font-size:11px;color:#74849c}.dot{width:7px;height:7px;border-radius:50%;background:#d5dfed}.bar span{margin-left:auto;margin-right:auto}iframe{width:744px;height:623px;border:0;background:#f5f7fb}.progress{position:absolute;bottom:0;height:4px;left:0;background:#185adb;width:0;animation:progress 50s linear forwards}@keyframes progress{to{width:100%}}</style><body><main class="stage"><section class="copy"><div class="brand"><img src="/icons/icon128.png">HistoryOut</div><div class="step" id="step">BROWSER HISTORY, MADE USEFUL</div><h1 id="title">Find your<br><span class="blue">way back.</span></h1><p class="lead" id="lead">Revisit your day. Resume your research. Keep a record that works for you.</p></section><div class="caption" id="caption">Your browsing history has more to offer than a long list of links.</div><div class="frame"><div class="bar"><i class="dot"></i><i class="dot"></i><i class="dot"></i><span id="frame-label">HistoryOut · Live working interface</span></div><iframe title="Working HistoryOut demo" src="/panel"></iframe></div><div class="note">Fictional demo history · Actual interface · No music or borrowed footage</div><div class="progress"></div></main></body></html>`;}
async function video(browser,origin){
 await fs.writeFile(path.join(ROOT,'source','video-stage.html'),videoStage());
 const context=await browser.newContext({viewport:{width:1280,height:720},locale:'en-GB',timezoneId:'Europe/Vilnius',acceptDownloads:true,recordVideo:{dir:path.join(ROOT,'video'),size:{width:1280,height:720}}});
 await context.addInitScript(installFixture);const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-05T14:00:00Z'));
 await page.goto(origin+'/launch/assets/source/video-stage.html');const f=page.frameLocator('iframe');await f.getByRole('button',{name:'Preview',exact:true}).waitFor();await sleep(600);const start=Date.now();
 const at=async seconds=>sleep(Math.max(0,start+seconds*1000-Date.now()));
 const text=async(step,title,lead,caption)=>page.evaluate(({step,title,lead,caption})=>{document.querySelector('#step').textContent=step;document.querySelector('#title').innerHTML=title;document.querySelector('#lead').textContent=lead;document.querySelector('#caption').textContent=caption;},{step,title,lead,caption});
 const scroll=async locator=>locator.evaluate(el=>window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-18,behavior:'smooth'}));
 await at(4);await text('01 / REVISIT YOUR DAY','Your day,<br><span class="blue">at a glance.</span>','See your visits, the pages you opened, and the sites you returned to.','Click Preview to read your current history. Everything stays on your device.');await f.getByRole('button',{name:'Preview',exact:true}).click();await f.getByRole('heading',{name:"Today's recap"}).waitFor();await scroll(f.getByRole('heading',{name:"Today's recap"}));
 await text('01 / REVISIT YOUR DAY','Your day,<br><span class="blue">at a glance.</span>','See your visits, the pages you opened, and the sites you returned to.','Click Preview to read your current history. Everything stays on your device.');console.log('Video: daily recap');
 await at(11);await text('02 / FIND WHAT MATTERS','Pick up your<br><span class="blue">research.</span>','Search titles or URLs, filter by website, and keep the latest visit to each page.','Find a useful page again, without retracing every step.');await scroll(f.getByRole('heading',{name:'Your recent trail'}));await f.getByRole('textbox',{name:'Search history titles or URLs'}).pressSequentially('research',{delay:95});await f.getByRole('checkbox',{name:/One row per URL/}).check();
 await text('02 / FIND WHAT MATTERS','Pick up your<br><span class="blue">research.</span>','Search titles or URLs, filter by website, and keep the latest visit to each page.','Find a useful page again, without retracing every step.');console.log('Video: search');
 await at(19);await text('03 / RETURN TO YOUR FLOW','Save the view.<br><span class="blue">Resume later.</span>','Keep your range, filters and export settings ready for the next time.','Saved views store your preferences, never a copy of your browsing history.');await f.getByRole('button',{name:'Save view',exact:true}).click();await f.getByRole('textbox',{name:'View name'}).pressSequentially('Website research',{delay:70});await f.getByRole('button',{name:'Save',exact:true}).click();await scroll(f.getByText('Your saved views',{exact:true}));
 await text('03 / RETURN TO YOUR FLOW','Save the view.<br><span class="blue">Resume later.</span>','Keep your range, filters and export settings ready for the next time.','Saved views store your preferences, never a copy of your browsing history.');console.log('Video: saved view');
 await at(27);await text('04 / EXPORT ONLY WHAT YOU NEED','A cleaner file.<br><span class="blue">Your choice.</span>','Choose CSV, JSON or HTML, plus the exact columns you want to keep.','Optional cleanup removes URL queries and fragments. It does not anonymize your history.');await f.getByRole('checkbox',{name:'Remove URL queries & fragments'}).check();await f.getByRole('button',{name:'HTML, readable in a browser',exact:true}).click();
 await f.getByLabel('Include',{exact:true}).click();const opts=f.getByRole('option');for(let i=0;i<await opts.count();i++){const opt=opts.nth(i);const name=(await opt.innerText()).split('\n')[0].trim();const checked=(await opt.getAttribute('aria-selected'))==='true';if(checked!==['date','title','url'].includes(name.toLowerCase()))await opt.click();}await page.keyboard.press('Escape');await sleep(450);await scroll(f.getByRole('heading',{name:'Your export'}));
 await text('04 / EXPORT ONLY WHAT YOU NEED','A cleaner file.<br><span class="blue">Your choice.</span>','Choose CSV, JSON or HTML, plus the exact columns you want to keep.','Optional cleanup removes URL queries and fragments. It does not anonymize your history.');console.log('Video: export options');
 await at(36);await text('05 / A RECORD YOU CAN USE','From a trail<br><span class="blue">to a useful file.</span>','Your matching pages, in a real downloaded HTML file with clickable links.','Export your selected pages to a readable HTML file.');const wd=page.waitForEvent('download');await f.getByRole('button',{name:/^Export \d/}).click();const dl=await wd;await dl.saveAs(path.join(ROOT,'video','demo-video-export.html'));await sleep(700);await page.locator('iframe').evaluate((el,url)=>el.src=url,origin+'/launch/assets/video/demo-video-export.html');
 await text('05 / A RECORD YOU CAN USE','From a trail<br><span class="blue">to a useful file.</span>','Your matching pages, in a real downloaded HTML file with clickable links.','This is the actual export. Open it, use it, and revisit the pages you need.');await page.locator('#frame-label').evaluate(el=>el.textContent='Actual downloaded HTML export');console.log('Video: actual downloaded file');
 await at(44);await text('FREE / LOCAL / NO ACCOUNT','Find your<br><span class="blue">way back.</span>','Get HistoryOut free.\nexportchromehistory.app','Revisit your day. Resume your research. Keep what matters.');
 await at(50.8);const recording=page.video();await context.close();const source=await recording.path();const dest=path.join(ROOT,'video','historyout-v2-demo.mp4');
 const encoded=spawnSync('ffmpeg',['-y','-i',source,'-ss','0.65','-t','50','-vf','scale=1280:720,fps=30','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-an','-movflags','+faststart',dest],{encoding:'utf8'});if(encoded.status!==0)throw new Error(encoded.stderr);
 await fs.rm(source);
 await fs.writeFile(path.join(ROOT,'video','historyout-v2-captions.srt'),`1\n00:00:00,000 --> 00:00:04,000\nFind your way back with HistoryOut.\n\n2\n00:00:04,000 --> 00:00:11,000\nPreview your day. Your history stays on your device.\n\n3\n00:00:11,000 --> 00:00:19,000\nSearch your research and keep the latest visit to each page.\n\n4\n00:00:19,000 --> 00:00:27,000\nSave your view to return to these settings later.\n\n5\n00:00:27,000 --> 00:00:36,000\nChoose columns and format. URL cleanup does not anonymize history.\n\n6\n00:00:36,000 --> 00:00:44,000\nA real downloaded HTML file, with clickable page links.\n\n7\n00:00:44,000 --> 00:00:50,000\nGet HistoryOut free at exportchromehistory.app.\n`);
 console.log('Video:',dest);
}
(async()=>{await folder();const server=await startServer();const browser=await chromium.launch({headless:true});try{if(!process.argv.includes('--video-only'))await screenshots(browser,server.origin);if(!process.argv.includes('--screenshots-only'))await video(browser,server.origin);}finally{await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
