"""Verify actual encoded output and retain measured delivery metadata."""
from pathlib import Path
import hashlib,json,re,subprocess
ROOT=Path(__file__).resolve().parents[1]
mp4=ROOT/'historyout-export-demo.mp4'
probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_format','-show_streams','-of','json',str(mp4)]))
video=next(s for s in probe['streams'] if s['codec_type']=='video');audio=next(s for s in probe['streams'] if s['codec_type']=='audio');duration=float(probe['format']['duration'])
voice=json.loads((ROOT/'source/voice-metrics.json').read_text());captions=json.loads((ROOT/'source/timed-captions.json').read_text())
text=json.loads((ROOT/'source/narration.json').read_text())[0]['text'];normalize=lambda s:re.sub(r'[^a-z0-9]','',s.lower())
for name in ['voice-transcript-check.json','final-mix-transcript.json']:
    result=json.loads((ROOT/'source'/name).read_text());assert normalize(result['text'])==normalize(text),name
mix=json.loads((ROOT/'source/audio-metrics.json').read_text())
raw_loudness=subprocess.run(['ffmpeg','-hide_banner','-i',str(mp4),'-af','loudnorm=I=-16:TP=-1:LRA=7:print_format=json','-f','null','-'],capture_output=True,text=True).stderr
loudness=json.loads(raw_loudness[raw_loudness.rfind('{'):raw_loudness.rfind('}')+1])
metadata={'title':'Export your browser history as CSV, JSON or HTML with HistoryOut','duration_seconds':duration,'width':video['width'],'height':video['height'],'fps':video['r_frame_rate'],'video_codec':video['codec_name'],'audio_codec':audio['codec_name'],'audio_channels':audio['channels'],'sample_rate':int(audio['sample_rate']),'bytes':mp4.stat().st_size,'sha256':hashlib.sha256(mp4.read_bytes()).hexdigest(),'mp4':mp4.name,'poster':'historyout-poster.png','captions_vtt':'historyout-captions.vtt','captions_srt':'historyout-captions.srt','transcript_text':text,'timed_captions':captions,'voice_file_start':voice['voice_file_start'],'speech_start':voice['speech_start'],'speech_end':voice['speech_end'],'raw_voice_duration':voice['raw_duration'],'raw_voice_end':voice['raw_audio_end'],'tail_seconds_after_raw_voice':round(duration-voice['raw_audio_end'],6),'tail_seconds_after_last_word':round(duration-voice['speech_end'],6),'words_per_minute':voice['words_per_minute_including_native_pauses'],'model':voice['voice_model'],'exaggeration':voice['exaggeration'],'cfg_weight':voice['cfg_weight'],'fixed_gain':voice['fixed_gain'],'tempo_changes':False,'pitch_changes':False,'internal_gap_edits':False,'speech_cuts':False,'loudness_integrated_lufs':float(loudness['input_i']),'true_peak_dbtp':float(loudness['input_tp']),'loudness_range_lu':float(loudness['input_lra']),'sample_peak_before_encode':mix['peak'],'click_count':mix['click_count'],'final_card_start':voice['final_card_start'],'final_card_text':'Export browser history. CSV · JSON · HTML. Free. Local. No account. Get HistoryOut free.','music_fade_start':voice['music_fade_start'],'music_fade_end':voice['music_fade_end'],'transition_seconds':.3,'voice_provenance':'A completely new local synthetic performance from the creator-authorized original reference. No inherited Qwen audio. Only constant gain and sample-rate conversion for mixing.','history':'Actual working UI and downloaded files; fictional QA records. Coffee promotions hidden with capture-only CSS. Production extension unchanged.','verification':'Exact words verified independently in raw voice and encoded MP4. Frames visually reviewed. Technical checks do not claim a human perceptual assessment.','production_bundle_sha256':hashlib.sha256((ROOT.parents[2]/'extension-unpacked/bundle.js').read_bytes()).hexdigest()}
(ROOT/'historyout-media.json').write_text(json.dumps(metadata,indent=2)+'\n');(ROOT/'source/loudness-check.json').write_text(json.dumps(loudness,indent=2)+'\n')
subprocess.run(['ffmpeg','-y','-loglevel','error','-ss','3.8','-i',str(mp4),'-frames:v','1','-update','1',str(ROOT/'historyout-poster.png')],check=True)
subprocess.run(['ffmpeg','-y','-loglevel','error','-ss',str(duration-.2),'-i',str(mp4),'-frames:v','1','-update','1',str(ROOT/'historyout-ending.png')],check=True)
times=[.7,3.8,8.7,9.5,11.4,14.2,16.7,18.8,22.0,duration-.2];frames=[round(t*30) for t in times];select='+'.join(f'eq(n,{n})' for n in frames)
subprocess.run(['ffmpeg','-y','-loglevel','error','-i',str(mp4),'-vf',f"select='{select}',scale=640:360,tile=2x5",'-frames:v','1','-update','1',str(ROOT/'review-contact-sheet.png')],check=True)
print(json.dumps({k:metadata[k] for k in ['duration_seconds','raw_voice_duration','speech_end','tail_seconds_after_raw_voice','loudness_integrated_lufs','true_peak_dbtp','sha256']},indent=2))
